name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Hello world test1
      id: hello-world-test1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Hello world test1
        setup-command: ''
        command: "./main"
        input: 1 2
        expected-output: '3'
        comparison-method: exact
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO-WORLD-TEST1_RESULTS: "${{steps.hello-world-test1.outputs.result}}"
      with:
        runners: hello-world-test1
